version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: fashion_recommender_db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - fashion_network

volumes:
  mongodb_data:
    driver: local

networks:
  fashion_network:
    driver: bridge
