name: Manage Labels

permissions:
  issues: write

on:
  push:
    paths:
      - '.github/labels.yaml'
  workflow_dispatch: # This allows manual triggering of the workflow

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install js-yaml

    - name: Manage Labels
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const yaml = require('js-yaml');
          const filePath = process.env.GITHUB_WORKSPACE + '/.github/labels.yaml';
          
          const fileContents = fs.readFileSync(filePath, 'utf8');
          const labels = yaml.load(fileContents);

          for (const label of labels) {
            const existingLabel = await github.issues.getLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: label.name
            }).catch(() => null);

            if (existingLabel) {
              await github.issues.updateLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: label.name,
                color: label.color,
                description: label.description,
              });
            } else {
              await github.issues.createLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: label.name,
                color: label.color,
                description: label.description,
              });
            }
          }
