name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
      - name: Generate Project Structure
        run: python scripts/update_readme.py > project_structure.txt

      - name: Check project structure output
        run: cat project_structure.txt
      
      - name: Update README
        run: |
          sed -i '/## Project Structure/{n;d;}' README.md
          sed -i "/## Project Structure/r project_structure.txt" README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Automated update of project structure in README"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
